### ISSUE TITLE
Disambiguate duplicate department labels using parent organization information

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss-labs/rialto-derivatives#68] opened 2018-09-18 17:13 UTC
<img width="580" alt="screen shot 2018-09-18 at 12 13 00 pm" src="https://user-images.githubusercontent.com/92044/45704332-38ca1600-bb3c-11e8-8769-3a8d805585ef.png">

**Comment by jcoyne** [comment] 2018-09-18 18:00
```
 => "http://rialto.stanford.edu/organizations/vice-provost-and-dean-of-research/administration"
2.5.1 :004 > Organization.find(1099).uri
  Organization Load (1.7ms)  SELECT  "organizations".* FROM "organizations" WHERE "organizations"."id" = $1 LIMIT $2  [["id", 1099], ["LIMIT", 1]]
 => "http://rialto.stanford.edu/organizations/stanford-law-school/administration"
```

Looks like they're administration departments in different containing organizations.

**Comment by peetucket** [comment] 2018-09-18 18:39
Determine number of dupe labels in full org data set to assess scope of problem

**Comment by justinlittman** [comment] 2018-09-18 19:17
The problem is worse than expected.

```
cat organizations.json | jq -r '..|.name?' | sort | uniq -c | sort -r | head -36
  22 Operations
  12 Administration
   7 Dean's Office
   5 Human Resources
   5 Finance
   4 Labs and Programs
   3 Student Services
   3 Information Systems
   3 Financial Aid
   3 External Relations
   3 Economics
   2 Vaden Health Center
   2 Technical Services
   2 Student Affairs
   2 SUNCAT Center for Interface Science and Catalysis
   2 Program-Faculty
   2 Program on Energy and Sustainable Development
   2 Primary Care Outcomes Research
   2 Organizational Behavior
   2 Nephrology
   2 Marketing
   2 Infectious Diseases
   2 Global Innovation Programs (GIPR)
   2 Functional Genomics Facility
   2 Finance and Administration
   2 Family & Community Medicine
   2 Executive Education Program
   2 Energy Modeling Forum
   2 Divisions, Labs and Programs
   2 Director's Office
   2 Development and External Relations
   2 Copy Center
   2 Computer Systems Laboratory
   2 Center on Food Security and the Environment
   2 Center for Biomedical Ethics
   2 Cancer Biology
```

**Comment by mjgiarlo** [comment] 2018-09-18 19:18
```
$ exe/extract call StanfordOrganizations > orgs.json
$ exe/transform call StanfordOrganizations -i orgs.json  > orgs.sparql
$ grep 'prefLabel> "' orgs.sparql  | cut -d\" -f2 | sort | uniq -c | sort -nr     
     22 Operations                                                                                                                                    
     12 Administration                                                                                                                                
      7 Dean's Office                                                                                                                                 
      5 Human Resources                                                                                                                               
      5 Finance                                                                                                                                       
      4 Labs and Programs                                                                                                                             
      3 Student Services                                                                                                                              
      3 Information Systems                                                                                                                           
      3 Financial Aid                                                                                                                                 
      3 External Relations                                                                                                                            
      3 Economics                                                                                                                                     
      2 Vaden Health Center                                                                                                                           
      2 Technical Services                                                                                                                            
      2 SUNCAT Center for Interface Science and Catalysis                                                                                             
      2 Student Affairs                                                                                                                               
      2 Program on Energy and Sustainable Development                                                                                                 
      2 Program-Faculty                                                                                                                               
      2 Primary Care Outcomes Research                                                                                                                
      2 Organizational Behavior                                                                                                                       
      2 Nephrology                                                                                                                                    
      2 Marketing                                                                                                                                     
      2 Infectious Diseases                                                                                                                           
      2 Global Innovation Programs (GIPR)                                                                                                             
      2 Functional Genomics Facility                                                                                                                  
      2 Finance and Administration                                                                                                                    
      2 Family & Community Medicine                                                                                                                   
      2 Executive Education Program                                                                                                                   
      2 Energy Modeling Forum                                                                                                                         
      2 Divisions, Labs and Programs                                                                                                                  
      2 Director's Office                                                                                                                             
      2 Development and External Relations                                                                                                            
      2 Copy Center                                                                                                                                   
      2 Computer Systems Laboratory                                                                                                                   
      2 Center on Food Security and the Environment                                                                                                   
      2 Center for Biomedical Ethics                                                                                                                  
      2 Cancer Biology                                                                         
```

**Comment by mjgiarlo** [comment] 2018-09-18 19:42
It's not the best algorithm but here's a potential avenue to explore to improve the quality of names coming out of ETL: 
```diff
diff --git a/lib/rialto/etl/configs/stanford_organizations_to_sparql_statements.rb b/lib/rialto/etl/configs/stanford_organizations_to_sparql_statements.rb
index 0de8ee1..7be4f10 100644
--- a/lib/rialto/etl/configs/stanford_organizations_to_sparql_statements.rb
+++ b/lib/rialto/etl/configs/stanford_organizations_to_sparql_statements.rb
@@ -15,6 +15,12 @@ settings do
   provide 'reader_class_name', 'Rialto::Etl::Readers::StanfordOrganizationsJsonReader'
 end
 
+def parents_from_alias(hierarchy)
+  hierarchy.split('/')[0...-1].map do |parent|
+    parent.split('-').map(&:capitalize).join(' ')
+  end.join(' / ')
+end
+
 # The named graph to place these triples into.
 to_field '@graph', literal(STANFORD_ORGANIZATIONS_GRAPH.to_s), single: true
 
@@ -45,7 +51,11 @@ to_field '@type', lambda { |json, accum|
 
 # Org label
 to_field '!label', literal(true)
-to_field '@label', extract_json('$.name'), single: true
+to_field '@label', lambda { |json, accum|
+  name = JsonPath.on(json, '$.name').first
+  hierarchy = JsonPath.on(json, '$.alias').first
+  accum << "#{name} (#{parents_from_alias(hierarchy)})"
+}, single: true
 
 # Org codes
 to_field '!' + DCTERMS.identifier.to_s, literal(true)
```

**Comment by justinlittman** [comment] 2018-09-19 12:38
I screwed up and committed directly to ETL master. However, here is a [fix](https://github.com/sul-dlss-labs/rialto-etl/commit/95954aa9e7689651b04352ba093e8d7d7accf796).

Take a look -- if there is any issue, I will undo the commit.

**Closed** 2018-09-19 16:02 UTC
Labels: bug, review
